### ISSUE TITLE
Game crashes with mod on a server

### ISSUE THREAD

**Issue by mrCupcakewithicecream** [Nic4Las/Minecraft-Enderite-Mod#27] opened 2021-02-21 18:00 UTC
The game crashes when we craft for example and it is only on a server.

Also please a 1.16.4 version.

**Comment by Nic4Las** [comment] 2021-05-02 12:01
I'm assuming you are using the forge version and that this is a duplicate of #23. We are working on it.

**Closed by Nic4Las** 2021-05-02 12:01 UTC
