### ISSUE TITLE
Enderite elytra chestplate not works

### ISSUE THREAD

**Issue by BlackBirdTrr** [Nic4Las/Minecraft-Enderite-Mod#44] opened 2021-07-27 02:24 UTC
Is mod works with origins mod

https://www.curseforge.com/minecraft/mc-mods/origins-forge

**Comment by geblinatorgr** [comment] 2021-10-30 15:58
> Is mod works with origins mod
> 
> https://www.curseforge.com/minecraft/mc-mods/origins-forge

are you saying that this fixes the issue?

**Comment by Nic4Las** [comment] 2022-01-22 12:26
I don't understand what the issue is here. Closing this for now. Feel free to reopen this issue.

**Closed by Nic4Las** 2022-01-22 12:26 UTC
