### ISSUE TITLE
Installing this mod resulted in EMI reload failure

### ISSUE THREAD

**Issue by shenyx110** [Nic4Las/Minecraft-Enderite-Mod#122] opened 2024-09-27 09:44 UTC
Installing this mod resulted in EMI reload failure
[minecraft-exported-logs-2024-09-27T17-43-22.log](https://github.com/user-attachments/files/17162316/minecraft-exported-logs-2024-09-27T17-43-22.log)
[minecraft-exported-crash-info-2024-09-27T17-43-27.zip](https://github.com/user-attachments/files/17162318/minecraft-exported-crash-info-2024-09-27T17-43-27.zip)
[minecraft-exported-logs-2024-09-27T17-42-58.log](https://github.com/user-attachments/files/17162319/minecraft-exported-logs-2024-09-27T17-42-58.log)

**Comment by Nic4Las** [comment] 2024-09-30 15:46
Sorry, we looked through the logs you provided, and from the logs, it doesn't look like the crash is our fault. I'm also unable to reproduce this crash using just Enderite, Architectury, and EMI on both NeoForge or Fabric. Closing this for now, as it seems unrelated to Enderite. Feel free to reopen if you can reproduce this using a minimal amount of mods.

**Closed by Nic4Las** 2024-09-30 15:46 UTC
